dist: bionic

language: scala
scala: 2.13.1

env:
  - PATH=$TRAVIS_BUILD_DIR/unix/bin:$PATH

# A few notes on caching:
# SBT is very picky when it comes to recompilation. It boils down to the modify time and path of the source and class
# files. If the modify time of the JVM changes, the full project is recompiled. This is why the openjdk version is left
# default; that version is already installed. Dynamic installation causes the modify time to be different for each
# travis run. Furthermore, travis uses tar for caching, which by default has insufficient accuracy in the modify time
# for SBT. That is why the executable is replaced with a script that flags tar to store the archive in posix format,
# which does offer sufficient resolution.

addons:
  sonarcloud:
    organization: utwente-fmt
    token:
      secure: "rN1xKIRlcnyPz0wtlmzF5AW04f57sPVmhDe3TjXWho84YWE5eu6avdV36NeS6PHrocKpcLY3PLLqtNs6FPMmlN2fBvLQs8Z0iEkhfrJv3moq9GuE8la6D4845iR7Kw+gtqbDS7cVDh9zZ33zVvgK+faLz6yy+NopXcyO4cxYPUhKypyvCGnPNxCLUuW8bq+0pV1xbuqhd+r18Zd+UQCiX5RE/1Zio5LuXLkPfO+fy1D7/OKwzA5sjWS2oNsIR9w5jRA7IVK4gbfm/wgkwkRhMDlezXpsSWTXQq0Ib8HgER3GkFjCF0rqtsEYKSvDuo80paVrbZEnT/lEu7+5UV5BbhN/pTaKW4or8b1dFbUOJTlxJXVXhO8VgdHO88OrKWlvq4KJjq48ZPchHx30lKHAeCVOW9m2lfFXM9I/8vnFQgQ7HEC+TvYwyWLqDv+ZNAJ9qQSYYJby5ZWaTRr306eERj1xFPrljbw/g9SpKMMM66C8PfbCgn06X/PeaycqrcgZLd1mYyKNB7+vGt9x4IN3wJAdV+H2Y0EYZuIF+GEX1D6+zYjFF7bZhl/xHW/oQC8PxxmE9D7QBU1SHhwOybCeujvbYk/7XrHVK2vic2KbScKyeTthJeqVUE616xImTyhJcVJti1AMchLdUmppsfTVRHkOG6HniLmIJIQpV+Ajz2k="

cache:
  directories:
   - ~/.cache/coursier
   - ~/.ivy2/cache
   - ~/.sbt

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

matrix:
  include:
    - script:
      - SPLIT=0/5 ./.travis/build.sh
    - script:
      - SPLIT=1/5 ./.travis/build.sh
    - script:
      - SPLIT=2/5 ./.travis/build.sh
    - script:
      - SPLIT=3/5 ./.travis/build.sh
    - script:
      - SPLIT=4/5 ./.travis/build.sh
    - script:
      - ./.travis/travis_fold.sh build "Build Vercors" "sbt compile"
      - ./.travis/travis_fold.sh sonar "Sonar" "sonar-scanner"
